// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/sendContactEmail.ts";
import * as $$$$$$$$$1 from "./actions/sendContactEmailDirect.ts";
import * as $$$$$$$$$$$0 from "./apps/deco/blog.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$2 from "./apps/deco/records.ts";
import * as $$$$$$$$$$$3 from "./apps/deco/resend.ts";
import * as $$$$$$$$$$$4 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/Atuacao.tsx";
import * as $$$$$$1 from "./sections/BlogPost.tsx";
import * as $$$$$$2 from "./sections/BlogPosts.tsx";
import * as $$$$$$3 from "./sections/ContactForm.tsx";
import * as $$$$$$4 from "./sections/Contato.tsx";
import * as $$$$$$5 from "./sections/EventosParticipacao.tsx";
import * as $$$$$$6 from "./sections/Footer.tsx";
import * as $$$$$$7 from "./sections/Header.tsx";
import * as $$$$$$8 from "./sections/Hero.tsx";
import * as $$$$$$9 from "./sections/Home/Eventos.tsx";
import * as $$$$$$10 from "./sections/Home/Midia.tsx";
import * as $$$$$$11 from "./sections/Home/Noticias.tsx";
import * as $$$$$$12 from "./sections/Home/Projetos.tsx";
import * as $$$$$$13 from "./sections/Home/Sobre.tsx";
import * as $$$$$$14 from "./sections/MainPost.tsx";
import * as $$$$$$15 from "./sections/MidiaLista.tsx";
import * as $$$$$$16 from "./sections/MidiaNoticiaDetalhe.tsx";
import * as $$$$$$17 from "./sections/PageTitle.tsx";
import * as $$$$$$18 from "./sections/Projeto/Documents.tsx";
import * as $$$$$$19 from "./sections/Projeto/Header.tsx";
import * as $$$$$$20 from "./sections/Projeto/HighlightNumbers.tsx";
import * as $$$$$$21 from "./sections/Projeto/Image.tsx";
import * as $$$$$$22 from "./sections/Projeto/Links.tsx";
import * as $$$$$$23 from "./sections/Projeto/MoreProjects.tsx";
import * as $$$$$$24 from "./sections/Projeto/TextBlock.tsx";
import * as $$$$$$25 from "./sections/Projetos.tsx";
import * as $$$$$$26 from "./sections/SimpleContactForm.tsx";
import * as $$$$$$27 from "./sections/SobreEquipe.tsx";
import * as $$$$$$28 from "./sections/SobreLeme.tsx";
import * as $$$$$$29 from "./sections/SobreMissaoValores.tsx";
import * as $$$$$$30 from "./sections/Theme/Theme.tsx";
import * as $$$$$$31 from "./sections/Transparencia.tsx";
import * as $$$$$$32 from "./sections/Watermark.tsx";

const manifest = {
  "sections": {
    "site/sections/Atuacao.tsx": $$$$$$0,
    "site/sections/BlogPost.tsx": $$$$$$1,
    "site/sections/BlogPosts.tsx": $$$$$$2,
    "site/sections/ContactForm.tsx": $$$$$$3,
    "site/sections/Contato.tsx": $$$$$$4,
    "site/sections/EventosParticipacao.tsx": $$$$$$5,
    "site/sections/Footer.tsx": $$$$$$6,
    "site/sections/Header.tsx": $$$$$$7,
    "site/sections/Hero.tsx": $$$$$$8,
    "site/sections/Home/Eventos.tsx": $$$$$$9,
    "site/sections/Home/Midia.tsx": $$$$$$10,
    "site/sections/Home/Noticias.tsx": $$$$$$11,
    "site/sections/Home/Projetos.tsx": $$$$$$12,
    "site/sections/Home/Sobre.tsx": $$$$$$13,
    "site/sections/MainPost.tsx": $$$$$$14,
    "site/sections/MidiaLista.tsx": $$$$$$15,
    "site/sections/MidiaNoticiaDetalhe.tsx": $$$$$$16,
    "site/sections/PageTitle.tsx": $$$$$$17,
    "site/sections/Projeto/Documents.tsx": $$$$$$18,
    "site/sections/Projeto/Header.tsx": $$$$$$19,
    "site/sections/Projeto/HighlightNumbers.tsx": $$$$$$20,
    "site/sections/Projeto/Image.tsx": $$$$$$21,
    "site/sections/Projeto/Links.tsx": $$$$$$22,
    "site/sections/Projeto/MoreProjects.tsx": $$$$$$23,
    "site/sections/Projeto/TextBlock.tsx": $$$$$$24,
    "site/sections/Projetos.tsx": $$$$$$25,
    "site/sections/SimpleContactForm.tsx": $$$$$$26,
    "site/sections/SobreEquipe.tsx": $$$$$$27,
    "site/sections/SobreLeme.tsx": $$$$$$28,
    "site/sections/SobreMissaoValores.tsx": $$$$$$29,
    "site/sections/Theme/Theme.tsx": $$$$$$30,
    "site/sections/Transparencia.tsx": $$$$$$31,
    "site/sections/Watermark.tsx": $$$$$$32,
  },
  "actions": {
    "site/actions/sendContactEmail.ts": $$$$$$$$$0,
    "site/actions/sendContactEmailDirect.ts": $$$$$$$$$1,
  },
  "apps": {
    "site/apps/deco/blog.ts": $$$$$$$$$$$0,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$1,
    "site/apps/deco/records.ts": $$$$$$$$$$$2,
    "site/apps/deco/resend.ts": $$$$$$$$$$$3,
    "site/apps/site.ts": $$$$$$$$$$$4,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
